version: '3.8'
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"      # Redis port
      - "8001:8001"      # RedisInsight port
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS="--save 60 1"  # Save every 60 seconds if at least 1 change

volumes:
  redis_data:
